# Generated by Django 4.0.5 on 2022-07-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de cliente')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre de cliente')),
                ('email', models.CharField(max_length=50, verbose_name='Email de cliente')),
                ('direccion', models.CharField(max_length=25, null=True, verbose_name='Direccion de cliente')),
                ('telefono', models.IntegerField(null=True, verbose_name='Telefono de cliente')),
                ('contrasena', models.CharField(max_length=20, null=True, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del producto')),
                ('precio', models.IntegerField(null=True, verbose_name='Precio del producto')),
                ('fechaFabricacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='Productos')),
            ],
        ),
    ]
